# Generated by Django 3.1.2 on 2020-10-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_photo_orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('portrait', 'Portrait')], default='horizontal', max_length=25),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
