# Generated by Django 3.1.2 on 2020-10-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20201010_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_type_parameters',
            new_name='survey_type_parameter',
        ),
    ]
